In [1]:
import numpy as np
from pandas import read_csv    

import time

from datetime import datetime


#target_folder="./time-data/evaluation/"
target_folder="./time-data/setup/"


sensors=["fridge"]
#sensors=["microwave","fridge","cubiertos","ollas"]
tags=["1","2"] #,"3","4","5","6"]


#labels=["None","1","2","3","4","5","6"]
labels=["None","1","2"]

y_true=[]
y_pred=[]

for i,sensor in enumerate(sensors):
    print("METRIC OF SENSOR ",sensor)
    gt=read_csv(target_folder+"gt-labelling-sensors/"+sensor+".tsv", sep="\t",parse_dates=True, na_values=0)
    sv=read_csv(target_folder+sensor+".matrix.tsv", sep="\t",parse_dates=True,decimal=",")
    print(gt.dtypes)
    print(gt)
    print(gt["TIME"])
    print(sv)
    print(sv["TIME"])

    gt=gt.fillna(0)
    for tx,tt in enumerate(gt["TIME"]):
        
        if(sum(gt.values[tx][2:])==0):
            maxI=0
        else:
            maxI=np.argmax(gt.values[tx][2:])+1
        #print("GT:",tx,tt, "user:",gt.values[tx][2:],maxI)
        y_true.append(maxI)
        
        
        
        tt2=datetime.strptime(tt, '%Y-%m-%d %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S')
        print(tt,tt2,np.where(sv["TIME"]==tt2))
        ty=np.where(sv["TIME"]==tt2)[0][0]
        if(sum(sv.values[ty][1:])==0):
            maxJ=0
        else:
            maxJ=np.argmax(sv.values[ty][1:])+1
        #print("PV:",ty,tt2, "user:",sv.values[ty][1:],maxJ)
        y_pred.append(maxJ)
        if(maxJ!=maxI):
            print(tt)
        

METRIC OF SENSOR  fridge
Ix        int64
TIME     object
1       float64
2       float64
3       float64
4       float64
5       float64
6       float64
dtype: object
        Ix                 TIME    1    2    3   4   5   6
0      268  2022-12-20 15:07:00  NaN  NaN  NaN NaN NaN NaN
1      292  2022-12-20 15:13:00  NaN  1.0  NaN NaN NaN NaN
2      358  2022-12-20 15:29:30  1.0  NaN  NaN NaN NaN NaN
3      360  2022-12-20 15:30:00  1.0  NaN  NaN NaN NaN NaN
4      365  2022-12-20 15:31:15  NaN  NaN  1.0 NaN NaN NaN
..     ...                  ...  ...  ...  ...  ..  ..  ..
108  13387  2022-12-22 21:46:45  1.0  NaN  NaN NaN NaN NaN
109  13395  2022-12-22 21:48:45  1.0  NaN  NaN NaN NaN NaN
110  13598  2022-12-22 22:39:30  NaN  1.0  NaN NaN NaN NaN
111  16510  2022-12-23 10:47:30  NaN  NaN  NaN NaN NaN NaN
112  16514  2022-12-23 10:48:30  NaN  NaN  NaN NaN NaN NaN

[113 rows x 8 columns]
0      2022-12-20 15:07:00
1      2022-12-20 15:13:00
2      2022-12-20 15:29:30
3      2022-12-20 15

In [2]:
print(y_true)
print(y_pred)

print(np.array(y_true).shape)


[0, 2, 1, 1, 3, 1, 2, 2, 4, 4, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5, 3, 3, 3, 3, 2, 2, 2, 2, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 6, 6, 6, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 4, 4, 1, 1, 3, 1, 1, 3, 3, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0, 0]
[0, 2, 1, 1, 0, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 1, 1, 2, 0, 0]
(113,)


In [3]:
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)
print(cm)
print('Classification Report')

print(classification_report(y_true, y_pred, target_names=labels))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(cmap=plt.cm.Blues)
plt.show()

[[ 5  0  0  0  0  0  0]
 [ 1 47  4  0  0  0  0]
 [ 0  2 35  0  0  0  0]
 [ 8  1  0  0  0  0  0]
 [ 1  2  2  0  0  0  0]
 [ 1  1  0  0  0  0  0]
 [ 1  0  2  0  0  0  0]]
Classification Report


ValueError: Number of classes, 7, does not match size of target_names, 3. Try specifying the labels parameter